### ISSUE TITLE
点聚合 除了搜索的 AMapPOI类型的 可不可以直接 我给它数组  就可以进行缩放 

### ISSUE THREAD

**Issue by BadSuNian** [amapapi/iOS_3D_ClusterAnnotation#3]
QuadTreeNodeData QuadTreeNodeDataForAMapPOI(AMapPOI\* poi)
{
    return QuadTreeNodeDataMake(poi.location.latitude, poi.location.longitude, (__bridge_retained void *)(poi));
}
这里 我可以  给他传一个数组 是MAPointAnnotation 类型的  然后进行聚合显示吗

**Comment by cysgit** [comment]
现在仅支持AMapPOI。AMapPOI存储POI信息，而这些POI会作为点聚合显示的ClusterAnnotation的property。

1）推荐做法：若用对MAPointAnnotation做点聚合，推荐转换为AMapPOI类型（仅需location字段不为空即可支持点聚合功能），再按教程步骤进行点聚合。

2）若不想引入AMapSearch包，需要修改ClusterAnnotation文件夹内的源码，将AMapPOI类型替换为MAPointAnnotation类型。对应到创建QuadTreeNodeData，修改如下

```
QuadTreeNodeData QuadTreeNodeDataForMAPointAnnotation(MAPointAnnotation* poi)
{
    return QuadTreeNodeDataMake(poi.coordinate.latitude, poi.coordinate.longitude, (__bridge_retained void *)(poi));
}
```

另需修改其他地方，注意MAPointAnnotation的coordinate与QuadTreeData的（x，y）的对应即可。

3）解释一个误区：`QuadTreeNodeData QuadTreeNodeDataForAMapPOI(AMapPOI* poi)` 这个方法只支持根据一个 AMapPOI数据，创建一个QuadTreeNode。
传递AMapPOI数组并转换成QuadTreeNode数组，请使用

```
//输入pois数组，输出dataArray数组，同时返回pois数组的boundingBox。
BoundingBox quadTreeNodeDataArrayForPOIs(QuadTreeNodeData *dataArray, NSArray * pois);
```

**Comment by BadSuNian** [comment]
我  把它转化程AMapPOI这个类型  存进去了    直接在你这个 demo上面 修改的  但是  现在 这个上面没有mark  了 
AFModel searchCar:SearchCarUrl leftHeightLongitude:113.74215513467789 leftHeightLatitude:42.830335107802128 rightLowLongtitude:118.05900692939758 rightLowLatitude:36.264631389647178 elapse:3600 Base64Str:[AFModel base64] block:^(id successObject) {
         NSMutableArray \* poiArry = [[NSMutableArray alloc] init];
         poiArry  = [successObject objectForKey:@"ret"];
         for (NSInteger i = 0; i < poiArry.count; i++) {
             NSString \* lat = [[poiArry objectAtIndex:i] objectForKey:@"lat"];
             NSString \* lng = [[poiArry objectAtIndex:i] objectForKey:@"lng"];
             AMapPOI \* poi = [[AMapPOI alloc] init];
             poi.location.longitude = [lng doubleValue];
             poi.location.latitude = [lat doubleValue];
             [_arry addObject:poi];
         }
         [self.coordinateQuadTree buildTreeWithPOIs:_arry];

```
} fblock:^(id failureError) {

 }];
```

这里面的 ——arry  是 我自定义的 一个 可变数组

**Comment by BadSuNian** [comment]
正在尝试 换类型  修改你的 model 里面的类

**Comment by cysgit** [comment]
刚才尝试了下，AMapPOI类型只有location属性不为空，其他属性都为空，是可以进行点聚合的。

你可以检查一下：
1）地图显示的范围是否包含了你传入的poi。
可以用这个方法保证显示所有的poi（pois是poi数组）：

```
/* 如果只有一个结果，设置其为中心点. */
    if (pois.count == 1)
    {
        self.mapView.centerCoordinate = [pois[0] coordinate];
    }
    /* 如果有多个结果, 设置地图使所有的annotation都可见. */
    else
    {
//调这个方法前，先确保已经建立四叉树，并且把聚合好的annotation都add到mapView了
        [self.mapView showAnnotations:self.mapView.annotations animated:NO];
    }‍
```

2）检查一下你的_arry数组是否为空。
3）检查一下coordinate数据是否合法。

**Comment by BadSuNian** [comment]
聚合成功了，但是现在缩放或者移动或者放大地图 他就崩溃在这里了

@implementation ClusterAnnotation

提示  ： Thread 1 ： EXC_BAD_ACCESS(code = 2，addres = 0x0)这我就跟纠结了。。。

**Comment by cysgit** [comment]
崩溃这个地方 是 哪个地方 调用的？

**Comment by BadSuNian** [comment]
这个 bug  改号了 但是 现在 我想清空  所有mark  怎么办。。我应该  怎么 清空你那里面的 东西  还有 我现在 想 当 有一个的 时候 我坐一些 操作 我发现  现在 一个 的 时候   我换了 annview  的 样式 不起作用

**Comment by cysgit** [comment]
1）若想清空mapView里所有annotation

``` objc
 [self.mapView removeAnnotations:self.mapView.annotations];
```

2）若想清空QuadTree

``` objc
[self.coordinateQuadTree clean];
```

---

换AnnotationView的样式，请修改
`ClusterAnnotationView`类里的`- (void)drawRect:(CGRect)rect`
或者更换为自定义的AnnotationView类。

**Comment by BadSuNian** [comment]
不起作用呀                                           [pois addObject:(__bridge AMapPOI *)data.data];
这句话 直接 就崩溃了

**Comment by cysgit** [comment]
是修改了AnnotationView的样式以后导致这句崩溃的吗？二者应该联系不大。
崩溃报什么错呢？
建QuadTree的时候你是否修改了QuadTreeNodeData的成员data存储的类型？是否如下存的是AMapPOI指针类型呢（data本身是void*类型）？ 

``` objc
QuadTreeNodeDataForAMapPOI(AMapPOI* poi)
{
    return QuadTreeNodeDataMake(poi.location.latitude, poi.location.longitude, (__bridge_retained void *)(poi));
}
```

`[pois addObject:(__bridge AMapPOI *)data.data];`这句是把QuadTreeNode的data转换回AMapPOI类型，以便数组pois存储该ClusterAnnotation包含的poi的信息，后续做PoiDetailView的展示使用。
